allowBuilds:
  '@prisma/engines': true
  better-sqlite3: true
  prisma: true

ignoredBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - better-sqlite3
