import Footer from "@/shared/components/Footer";
import LayoutContainer from "@/shared/components/LayoutContainer";
import Navbar from "@/shared/components/Navbar";

import type { Metadata } from "next";
import StoreBreadcrumb from "./_components/StoreBreadcrumb";

export const metadata: Metadata = {
  title: "in store layout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Navbar />
      <StoreBreadcrumb />
      <LayoutContainer>
        {children}
      </LayoutContainer>
      <Footer />
    </div>
  );
}
