import { cn } from "@/lib/utils";
import MainProvider from "@/providers";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { google } from "better-auth";

export const vazir = localFont({
  src: [
    {
      path: "../fonts/Vazir-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/Vazir.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Vazir-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/Vazir-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other:{
    google:'notranslate'
  }
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={cn("h-full", "antialiased", vazir.className)}
    >
      {/* <body className="min-h-full max-w-360 min-w-97.5 mx-auto"> */}
      <body className="min-h-full max-w-97.5 mx-auto">
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
}
