import Footer from "@/shared/components/Footer";
import LayoutContainer from "@/shared/components/LayoutContainer";
import Navbar from "@/shared/components/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "main layout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <Navbar />
      <LayoutContainer>{children}</LayoutContainer>
      <Footer />
    </main>
  );
}
