import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbList,
  BreadcrumbSeparator,
} from "@/shared/components/ui/breadcrumb";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "in store layout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {/* - breadcrumb */}
      {/* <Breadcrumb className="">
        <BreadcrumbList className="flex flex-nowrap overflow-x-auto no-scrollbar gap-1">
          <BreadcrumbItem>صفحه اصلی</BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>دسته بندی محصولات</BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>لباس مجلسی</BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>لباس مجلس میدی </BreadcrumbItem>
        </BreadcrumbList>
      </Breadcrumb> */}
      <Breadcrumb className="">
        <BreadcrumbList className="bg-red-400 flex flex-nowrap overflow-x-auto no-scrollbar gap-1">
          <BreadcrumbItem>صفحه اصلی</BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>دسته بندی محصولات</BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>لباس مجلسی</BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>لباس مجلس میدی </BreadcrumbItem>
        </BreadcrumbList>
      </Breadcrumb>
      {children}
    </div>
  );
}
