import LayoutContainer from "@/shared/components/LayoutContainer";
import Navbar from "@/shared/components/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "in checkout layout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Navbar />
      <LayoutContainer className="pb-16 pt-6">
        {children}
      </LayoutContainer>
    </div>
  );
}
